package sg.edu.smu.livelabs.mobicom.models.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ATTENDEE_ENTITY".
 */
public class AttendeeEntity {

    private Long id;
    private Long UID;
    private String name;
    private String firstName;
    private String email;
    private String userHandle;
    private String role;
    private String designation;
    private String description;
    private String avatar;
    private String status;
    private java.util.Date registerTime;
    private Boolean star;
    private String interests;

    public AttendeeEntity() {
    }

    public AttendeeEntity(Long id) {
        this.id = id;
    }

    public AttendeeEntity(Long id, Long UID, String name, String firstName, String email, String userHandle, String role, String designation, String description, String avatar, String status, java.util.Date registerTime, Boolean star, String interests) {
        this.id = id;
        this.UID = UID;
        this.name = name;
        this.firstName = firstName;
        this.email = email;
        this.userHandle = userHandle;
        this.role = role;
        this.designation = designation;
        this.description = description;
        this.avatar = avatar;
        this.status = status;
        this.registerTime = registerTime;
        this.star = star;
        this.interests = interests;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUID() {
        return UID;
    }

    public void setUID(Long UID) {
        this.UID = UID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUserHandle() {
        return userHandle;
    }

    public void setUserHandle(String userHandle) {
        this.userHandle = userHandle;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getDesignation() {
        return designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public java.util.Date getRegisterTime() {
        return registerTime;
    }

    public void setRegisterTime(java.util.Date registerTime) {
        this.registerTime = registerTime;
    }

    public Boolean getStar() {
        return star;
    }

    public void setStar(Boolean star) {
        this.star = star;
    }

    public String getInterests() {
        return interests;
    }

    public void setInterests(String interests) {
        this.interests = interests;
    }

}
