package sg.edu.smu.livelabs.mobicom.models.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHAT_ROOM_ENTITY".
 */
public class ChatRoomEntity {

    private Long id;
    private String title;
    private String avatar;
    private String userIds;
    private Long serverId;
    private Long admin;
    private Boolean isGroup;
    private Long lastUserId;
    private String userNames;
    private String phoneNumbers;
    private String emails;
    private String avatarIds;
    private String lastMessage;
    private java.util.Date lastMessageTime;
    private java.util.Date lastUpdated;
    private Long owner;
    private Integer unread;
    private String status;
    private String memberStatus;

    public ChatRoomEntity() {
    }

    public ChatRoomEntity(Long id) {
        this.id = id;
    }

    public ChatRoomEntity(Long id, String title, String avatar, String userIds, Long serverId, Long admin, Boolean isGroup, Long lastUserId, String userNames, String phoneNumbers, String emails, String avatarIds, String lastMessage, java.util.Date lastMessageTime, java.util.Date lastUpdated, Long owner, Integer unread, String status, String memberStatus) {
        this.id = id;
        this.title = title;
        this.avatar = avatar;
        this.userIds = userIds;
        this.serverId = serverId;
        this.admin = admin;
        this.isGroup = isGroup;
        this.lastUserId = lastUserId;
        this.userNames = userNames;
        this.phoneNumbers = phoneNumbers;
        this.emails = emails;
        this.avatarIds = avatarIds;
        this.lastMessage = lastMessage;
        this.lastMessageTime = lastMessageTime;
        this.lastUpdated = lastUpdated;
        this.owner = owner;
        this.unread = unread;
        this.status = status;
        this.memberStatus = memberStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getUserIds() {
        return userIds;
    }

    public void setUserIds(String userIds) {
        this.userIds = userIds;
    }

    public Long getServerId() {
        return serverId;
    }

    public void setServerId(Long serverId) {
        this.serverId = serverId;
    }

    public Long getAdmin() {
        return admin;
    }

    public void setAdmin(Long admin) {
        this.admin = admin;
    }

    public Boolean getIsGroup() {
        return isGroup;
    }

    public void setIsGroup(Boolean isGroup) {
        this.isGroup = isGroup;
    }

    public Long getLastUserId() {
        return lastUserId;
    }

    public void setLastUserId(Long lastUserId) {
        this.lastUserId = lastUserId;
    }

    public String getUserNames() {
        return userNames;
    }

    public void setUserNames(String userNames) {
        this.userNames = userNames;
    }

    public String getPhoneNumbers() {
        return phoneNumbers;
    }

    public void setPhoneNumbers(String phoneNumbers) {
        this.phoneNumbers = phoneNumbers;
    }

    public String getEmails() {
        return emails;
    }

    public void setEmails(String emails) {
        this.emails = emails;
    }

    public String getAvatarIds() {
        return avatarIds;
    }

    public void setAvatarIds(String avatarIds) {
        this.avatarIds = avatarIds;
    }

    public String getLastMessage() {
        return lastMessage;
    }

    public void setLastMessage(String lastMessage) {
        this.lastMessage = lastMessage;
    }

    public java.util.Date getLastMessageTime() {
        return lastMessageTime;
    }

    public void setLastMessageTime(java.util.Date lastMessageTime) {
        this.lastMessageTime = lastMessageTime;
    }

    public java.util.Date getLastUpdated() {
        return lastUpdated;
    }

    public void setLastUpdated(java.util.Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    public Long getOwner() {
        return owner;
    }

    public void setOwner(Long owner) {
        this.owner = owner;
    }

    public Integer getUnread() {
        return unread;
    }

    public void setUnread(Integer unread) {
        this.unread = unread;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getMemberStatus() {
        return memberStatus;
    }

    public void setMemberStatus(String memberStatus) {
        this.memberStatus = memberStatus;
    }

}
