package sg.edu.smu.livelabs.mobicom.models.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHAT_MESSAGE_ENTITY".
 */
public class ChatMessageEntity {

    private Long id;
    private String msg;
    private Long userId;
    private java.util.Date lastUpdated;
    private Long chatRoomId;
    private Long owner;
    private Integer status;
    private Long serverId;
    private Boolean isNotification;

    public ChatMessageEntity() {
    }

    public ChatMessageEntity(Long id) {
        this.id = id;
    }

    public ChatMessageEntity(Long id, String msg, Long userId, java.util.Date lastUpdated, Long chatRoomId, Long owner, Integer status, Long serverId, Boolean isNotification) {
        this.id = id;
        this.msg = msg;
        this.userId = userId;
        this.lastUpdated = lastUpdated;
        this.chatRoomId = chatRoomId;
        this.owner = owner;
        this.status = status;
        this.serverId = serverId;
        this.isNotification = isNotification;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public java.util.Date getLastUpdated() {
        return lastUpdated;
    }

    public void setLastUpdated(java.util.Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    public Long getChatRoomId() {
        return chatRoomId;
    }

    public void setChatRoomId(Long chatRoomId) {
        this.chatRoomId = chatRoomId;
    }

    public Long getOwner() {
        return owner;
    }

    public void setOwner(Long owner) {
        this.owner = owner;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getServerId() {
        return serverId;
    }

    public void setServerId(Long serverId) {
        this.serverId = serverId;
    }

    public Boolean getIsNotification() {
        return isNotification;
    }

    public void setIsNotification(Boolean isNotification) {
        this.isNotification = isNotification;
    }

}
