package sg.edu.smu.livelabs.mobicom.models.data;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import sg.edu.smu.livelabs.mobicom.models.data.CommentEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMMENT_ENTITY".
*/
public class CommentEntityDao extends AbstractDao<CommentEntity, Long> {

    public static final String TABLENAME = "COMMENT_ENTITY";

    /**
     * Properties of entity CommentEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CommentHandle = new Property(1, String.class, "commentHandle", false, "COMMENT_HANDLE");
        public final static Property TopicHandle = new Property(2, String.class, "topicHandle", false, "TOPIC_HANDLE");
        public final static Property CreatedTime = new Property(3, java.util.Date.class, "createdTime", false, "CREATED_TIME");
        public final static Property UserHandle = new Property(4, String.class, "userHandle", false, "USER_HANDLE");
        public final static Property Text = new Property(5, String.class, "text", false, "TEXT");
        public final static Property TotalLikeCount = new Property(6, Long.class, "totalLikeCount", false, "TOTAL_LIKE_COUNT");
        public final static Property UserFullName = new Property(7, String.class, "userFullName", false, "USER_FULL_NAME");
        public final static Property UserPhotoUrl = new Property(8, String.class, "userPhotoUrl", false, "USER_PHOTO_URL");
        public final static Property Liked = new Property(9, Boolean.class, "liked", false, "LIKED");
        public final static Property Synced = new Property(10, Boolean.class, "synced", false, "SYNCED");
    };


    public CommentEntityDao(DaoConfig config) {
        super(config);
    }
    
    public CommentEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMMENT_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ASC ," + // 0: id
                "\"COMMENT_HANDLE\" TEXT," + // 1: commentHandle
                "\"TOPIC_HANDLE\" TEXT," + // 2: topicHandle
                "\"CREATED_TIME\" INTEGER," + // 3: createdTime
                "\"USER_HANDLE\" TEXT," + // 4: userHandle
                "\"TEXT\" TEXT," + // 5: text
                "\"TOTAL_LIKE_COUNT\" INTEGER," + // 6: totalLikeCount
                "\"USER_FULL_NAME\" TEXT," + // 7: userFullName
                "\"USER_PHOTO_URL\" TEXT," + // 8: userPhotoUrl
                "\"LIKED\" INTEGER," + // 9: liked
                "\"SYNCED\" INTEGER);"); // 10: synced
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_COMMENT_ENTITY_COMMENT_HANDLE ON COMMENT_ENTITY" +
                " (\"COMMENT_HANDLE\");");
        db.execSQL("CREATE INDEX " + constraint + "IDX_COMMENT_ENTITY_TOPIC_HANDLE ON COMMENT_ENTITY" +
                " (\"TOPIC_HANDLE\");");
        db.execSQL("CREATE INDEX " + constraint + "IDX_COMMENT_ENTITY_CREATED_TIME ON COMMENT_ENTITY" +
                " (\"CREATED_TIME\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMMENT_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CommentEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String commentHandle = entity.getCommentHandle();
        if (commentHandle != null) {
            stmt.bindString(2, commentHandle);
        }
 
        String topicHandle = entity.getTopicHandle();
        if (topicHandle != null) {
            stmt.bindString(3, topicHandle);
        }
 
        java.util.Date createdTime = entity.getCreatedTime();
        if (createdTime != null) {
            stmt.bindLong(4, createdTime.getTime());
        }
 
        String userHandle = entity.getUserHandle();
        if (userHandle != null) {
            stmt.bindString(5, userHandle);
        }
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(6, text);
        }
 
        Long totalLikeCount = entity.getTotalLikeCount();
        if (totalLikeCount != null) {
            stmt.bindLong(7, totalLikeCount);
        }
 
        String userFullName = entity.getUserFullName();
        if (userFullName != null) {
            stmt.bindString(8, userFullName);
        }
 
        String userPhotoUrl = entity.getUserPhotoUrl();
        if (userPhotoUrl != null) {
            stmt.bindString(9, userPhotoUrl);
        }
 
        Boolean liked = entity.getLiked();
        if (liked != null) {
            stmt.bindLong(10, liked ? 1L: 0L);
        }
 
        Boolean synced = entity.getSynced();
        if (synced != null) {
            stmt.bindLong(11, synced ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CommentEntity readEntity(Cursor cursor, int offset) {
        CommentEntity entity = new CommentEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // commentHandle
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // topicHandle
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // createdTime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // userHandle
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // text
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // totalLikeCount
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // userFullName
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // userPhotoUrl
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0, // liked
            cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0 // synced
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CommentEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCommentHandle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTopicHandle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCreatedTime(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setUserHandle(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setText(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTotalLikeCount(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setUserFullName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setUserPhotoUrl(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setLiked(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0);
        entity.setSynced(cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CommentEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CommentEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
