package sg.edu.smu.livelabs.mobicom.models.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COMMENT_ENTITY".
 */
public class CommentEntity {

    private Long id;
    private String commentHandle;
    private String topicHandle;
    private java.util.Date createdTime;
    private String userHandle;
    private String text;
    private Long totalLikeCount;
    private String userFullName;
    private String userPhotoUrl;
    private Boolean liked;
    private Boolean synced;

    public CommentEntity() {
    }

    public CommentEntity(Long id) {
        this.id = id;
    }

    public CommentEntity(Long id, String commentHandle, String topicHandle, java.util.Date createdTime, String userHandle, String text, Long totalLikeCount, String userFullName, String userPhotoUrl, Boolean liked, Boolean synced) {
        this.id = id;
        this.commentHandle = commentHandle;
        this.topicHandle = topicHandle;
        this.createdTime = createdTime;
        this.userHandle = userHandle;
        this.text = text;
        this.totalLikeCount = totalLikeCount;
        this.userFullName = userFullName;
        this.userPhotoUrl = userPhotoUrl;
        this.liked = liked;
        this.synced = synced;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCommentHandle() {
        return commentHandle;
    }

    public void setCommentHandle(String commentHandle) {
        this.commentHandle = commentHandle;
    }

    public String getTopicHandle() {
        return topicHandle;
    }

    public void setTopicHandle(String topicHandle) {
        this.topicHandle = topicHandle;
    }

    public java.util.Date getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(java.util.Date createdTime) {
        this.createdTime = createdTime;
    }

    public String getUserHandle() {
        return userHandle;
    }

    public void setUserHandle(String userHandle) {
        this.userHandle = userHandle;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Long getTotalLikeCount() {
        return totalLikeCount;
    }

    public void setTotalLikeCount(Long totalLikeCount) {
        this.totalLikeCount = totalLikeCount;
    }

    public String getUserFullName() {
        return userFullName;
    }

    public void setUserFullName(String userFullName) {
        this.userFullName = userFullName;
    }

    public String getUserPhotoUrl() {
        return userPhotoUrl;
    }

    public void setUserPhotoUrl(String userPhotoUrl) {
        this.userPhotoUrl = userPhotoUrl;
    }

    public Boolean getLiked() {
        return liked;
    }

    public void setLiked(Boolean liked) {
        this.liked = liked;
    }

    public Boolean getSynced() {
        return synced;
    }

    public void setSynced(Boolean synced) {
        this.synced = synced;
    }

}
