package sg.edu.smu.livelabs.mobicom.models.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GAME_LIST_ENTITY".
 */
public class GameListEntity {

    private Long id;
    private String gameName;
    private String keyword;
    private String description;
    private String imageURL;
    private String status;
    private java.util.Date insertTime;
    private java.util.Date lastUpdate;

    public GameListEntity() {
    }

    public GameListEntity(Long id) {
        this.id = id;
    }

    public GameListEntity(Long id, String gameName, String keyword, String description, String imageURL, String status, java.util.Date insertTime, java.util.Date lastUpdate) {
        this.id = id;
        this.gameName = gameName;
        this.keyword = keyword;
        this.description = description;
        this.imageURL = imageURL;
        this.status = status;
        this.insertTime = insertTime;
        this.lastUpdate = lastUpdate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGameName() {
        return gameName;
    }

    public void setGameName(String gameName) {
        this.gameName = gameName;
    }

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getImageURL() {
        return imageURL;
    }

    public void setImageURL(String imageURL) {
        this.imageURL = imageURL;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public java.util.Date getInsertTime() {
        return insertTime;
    }

    public void setInsertTime(java.util.Date insertTime) {
        this.insertTime = insertTime;
    }

    public java.util.Date getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(java.util.Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

}
