package sg.edu.smu.livelabs.mobicom.models.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GAME_ENTITY".
 */
public class GameEntity {

    private Long id;
    private String gameName;

    public GameEntity() {
    }

    public GameEntity(Long id) {
        this.id = id;
    }

    public GameEntity(Long id, String gameName) {
        this.id = id;
        this.gameName = gameName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGameName() {
        return gameName;
    }

    public void setGameName(String gameName) {
        this.gameName = gameName;
    }

}
