package sg.edu.smu.livelabs.mobicom.models.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ICE_BREAKER_LEADER_BOARD_ENTITY".
 */
public class IceBreakerLeaderBoardEntity {

    private Long id;
    private Long userId;
    private String name;
    private String emailId;
    private String desig;
    private String avatarId;
    private Integer count;

    public IceBreakerLeaderBoardEntity() {
    }

    public IceBreakerLeaderBoardEntity(Long id) {
        this.id = id;
    }

    public IceBreakerLeaderBoardEntity(Long id, Long userId, String name, String emailId, String desig, String avatarId, Integer count) {
        this.id = id;
        this.userId = userId;
        this.name = name;
        this.emailId = emailId;
        this.desig = desig;
        this.avatarId = avatarId;
        this.count = count;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmailId() {
        return emailId;
    }

    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    public String getDesig() {
        return desig;
    }

    public void setDesig(String desig) {
        this.desig = desig;
    }

    public String getAvatarId() {
        return avatarId;
    }

    public void setAvatarId(String avatarId) {
        this.avatarId = avatarId;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

}
