package sg.edu.smu.livelabs.mobicom.models.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INBOX_ENTITY".
 */
public class InboxEntity {

    private Long id;
    private java.util.Date DateTime;
    private Long notificationID;
    private String title;
    private String message;
    private Boolean read;
    private Integer type;

    public InboxEntity() {
    }

    public InboxEntity(Long id) {
        this.id = id;
    }

    public InboxEntity(Long id, java.util.Date DateTime, Long notificationID, String title, String message, Boolean read, Integer type) {
        this.id = id;
        this.DateTime = DateTime;
        this.notificationID = notificationID;
        this.title = title;
        this.message = message;
        this.read = read;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getDateTime() {
        return DateTime;
    }

    public void setDateTime(java.util.Date DateTime) {
        this.DateTime = DateTime;
    }

    public Long getNotificationID() {
        return notificationID;
    }

    public void setNotificationID(Long notificationID) {
        this.notificationID = notificationID;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Boolean getRead() {
        return read;
    }

    public void setRead(Boolean read) {
        this.read = read;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
