package sg.edu.smu.livelabs.mobicom.models.data;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import sg.edu.smu.livelabs.mobicom.models.data.InboxEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INBOX_ENTITY".
*/
public class InboxEntityDao extends AbstractDao<InboxEntity, Long> {

    public static final String TABLENAME = "INBOX_ENTITY";

    /**
     * Properties of entity InboxEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DateTime = new Property(1, java.util.Date.class, "DateTime", false, "DATE_TIME");
        public final static Property NotificationID = new Property(2, Long.class, "notificationID", false, "NOTIFICATION_ID");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property Message = new Property(4, String.class, "message", false, "MESSAGE");
        public final static Property Read = new Property(5, Boolean.class, "read", false, "READ");
        public final static Property Type = new Property(6, Integer.class, "type", false, "TYPE");
    };


    public InboxEntityDao(DaoConfig config) {
        super(config);
    }
    
    public InboxEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INBOX_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DATE_TIME\" INTEGER," + // 1: DateTime
                "\"NOTIFICATION_ID\" INTEGER," + // 2: notificationID
                "\"TITLE\" TEXT," + // 3: title
                "\"MESSAGE\" TEXT," + // 4: message
                "\"READ\" INTEGER," + // 5: read
                "\"TYPE\" INTEGER);"); // 6: type
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_INBOX_ENTITY_DATE_TIME ON INBOX_ENTITY" +
                " (\"DATE_TIME\");");
        db.execSQL("CREATE INDEX " + constraint + "IDX_INBOX_ENTITY_NOTIFICATION_ID ON INBOX_ENTITY" +
                " (\"NOTIFICATION_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INBOX_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, InboxEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        java.util.Date DateTime = entity.getDateTime();
        if (DateTime != null) {
            stmt.bindLong(2, DateTime.getTime());
        }
 
        Long notificationID = entity.getNotificationID();
        if (notificationID != null) {
            stmt.bindLong(3, notificationID);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(5, message);
        }
 
        Boolean read = entity.getRead();
        if (read != null) {
            stmt.bindLong(6, read ? 1L: 0L);
        }
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(7, type);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public InboxEntity readEntity(Cursor cursor, int offset) {
        InboxEntity entity = new InboxEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // DateTime
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // notificationID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // title
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // message
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // read
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6) // type
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, InboxEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDateTime(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setNotificationID(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMessage(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setRead(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setType(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(InboxEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(InboxEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
