package sg.edu.smu.livelabs.mobicom.models.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INTERESTS_ENTITY".
 */
public class InterestsEntity {

    private Long id;
    private String interest;
    private java.util.Date lastUpdated;

    public InterestsEntity() {
    }

    public InterestsEntity(Long id) {
        this.id = id;
    }

    public InterestsEntity(Long id, String interest, java.util.Date lastUpdated) {
        this.id = id;
        this.interest = interest;
        this.lastUpdated = lastUpdated;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getInterest() {
        return interest;
    }

    public void setInterest(String interest) {
        this.interest = interest;
    }

    public java.util.Date getLastUpdated() {
        return lastUpdated;
    }

    public void setLastUpdated(java.util.Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

}
