package sg.edu.smu.livelabs.mobicom.models.data;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PAPER_EVENT".
*/
public class PaperEventDao extends AbstractDao<PaperEvent, Long> {

    public static final String TABLENAME = "PAPER_EVENT";

    /**
     * Properties of entity PaperEvent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ServerId = new Property(1, Long.class, "ServerId", false, "SERVER_ID");
        public final static Property Title = new Property(2, String.class, "Title", false, "TITLE");
        public final static Property PdfLink = new Property(3, String.class, "pdfLink", false, "PDF_LINK");
        public final static Property EpubLink = new Property(4, String.class, "epubLink", false, "EPUB_LINK");
        public final static Property Authors = new Property(5, String.class, "authors", false, "AUTHORS");
        public final static Property EventTime = new Property(6, java.util.Date.class, "eventTime", false, "EVENT_TIME");
    };


    public PaperEventDao(DaoConfig config) {
        super(config);
    }
    
    public PaperEventDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PAPER_EVENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ASC ," + // 0: id
                "\"SERVER_ID\" INTEGER," + // 1: ServerId
                "\"TITLE\" TEXT," + // 2: Title
                "\"PDF_LINK\" TEXT," + // 3: pdfLink
                "\"EPUB_LINK\" TEXT," + // 4: epubLink
                "\"AUTHORS\" TEXT," + // 5: authors
                "\"EVENT_TIME\" INTEGER);"); // 6: eventTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PAPER_EVENT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PaperEvent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long ServerId = entity.getServerId();
        if (ServerId != null) {
            stmt.bindLong(2, ServerId);
        }
 
        String Title = entity.getTitle();
        if (Title != null) {
            stmt.bindString(3, Title);
        }
 
        String pdfLink = entity.getPdfLink();
        if (pdfLink != null) {
            stmt.bindString(4, pdfLink);
        }
 
        String epubLink = entity.getEpubLink();
        if (epubLink != null) {
            stmt.bindString(5, epubLink);
        }
 
        String authors = entity.getAuthors();
        if (authors != null) {
            stmt.bindString(6, authors);
        }
 
        java.util.Date eventTime = entity.getEventTime();
        if (eventTime != null) {
            stmt.bindLong(7, eventTime.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PaperEvent readEntity(Cursor cursor, int offset) {
        PaperEvent entity = new PaperEvent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // ServerId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // pdfLink
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // epubLink
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // authors
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)) // eventTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PaperEvent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setServerId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPdfLink(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setEpubLink(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAuthors(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setEventTime(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PaperEvent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PaperEvent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
