package sg.edu.smu.livelabs.mobicom.models.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SCAVENGER_WINNERS_ENTITY".
 */
public class ScavengerWinnersEntity {

    private Long huntId;
    private String name;
    private String emailId;
    private String avatarId;

    public ScavengerWinnersEntity() {
    }

    public ScavengerWinnersEntity(Long huntId, String name, String emailId, String avatarId) {
        this.huntId = huntId;
        this.name = name;
        this.emailId = emailId;
        this.avatarId = avatarId;
    }

    public Long getHuntId() {
        return huntId;
    }

    public void setHuntId(Long huntId) {
        this.huntId = huntId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmailId() {
        return emailId;
    }

    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    public String getAvatarId() {
        return avatarId;
    }

    public void setAvatarId(String avatarId) {
        this.avatarId = avatarId;
    }

}
