package sg.edu.smu.livelabs.mobicom.models.data;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import sg.edu.smu.livelabs.mobicom.models.data.ScavengerWinnersEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SCAVENGER_WINNERS_ENTITY".
*/
public class ScavengerWinnersEntityDao extends AbstractDao<ScavengerWinnersEntity, Void> {

    public static final String TABLENAME = "SCAVENGER_WINNERS_ENTITY";

    /**
     * Properties of entity ScavengerWinnersEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property HuntId = new Property(0, Long.class, "huntId", false, "HUNT_ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property EmailId = new Property(2, String.class, "emailId", false, "EMAIL_ID");
        public final static Property AvatarId = new Property(3, String.class, "avatarId", false, "AVATAR_ID");
    };


    public ScavengerWinnersEntityDao(DaoConfig config) {
        super(config);
    }
    
    public ScavengerWinnersEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SCAVENGER_WINNERS_ENTITY\" (" + //
                "\"HUNT_ID\" INTEGER," + // 0: huntId
                "\"NAME\" TEXT," + // 1: name
                "\"EMAIL_ID\" TEXT," + // 2: emailId
                "\"AVATAR_ID\" TEXT);"); // 3: avatarId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SCAVENGER_WINNERS_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ScavengerWinnersEntity entity) {
        stmt.clearBindings();
 
        Long huntId = entity.getHuntId();
        if (huntId != null) {
            stmt.bindLong(1, huntId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String emailId = entity.getEmailId();
        if (emailId != null) {
            stmt.bindString(3, emailId);
        }
 
        String avatarId = entity.getAvatarId();
        if (avatarId != null) {
            stmt.bindString(4, avatarId);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public ScavengerWinnersEntity readEntity(Cursor cursor, int offset) {
        ScavengerWinnersEntity entity = new ScavengerWinnersEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // huntId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // emailId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // avatarId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ScavengerWinnersEntity entity, int offset) {
        entity.setHuntId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setEmailId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAvatarId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(ScavengerWinnersEntity entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(ScavengerWinnersEntity entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
