package sg.edu.smu.livelabs.mobicom.models.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SEARCH_KEY_ENTITY".
 */
public class SearchKeyEntity {

    private Long id;
    private String key;
    private Boolean checked;

    public SearchKeyEntity() {
    }

    public SearchKeyEntity(Long id) {
        this.id = id;
    }

    public SearchKeyEntity(Long id, String key, Boolean checked) {
        this.id = id;
        this.key = key;
        this.checked = checked;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public Boolean getChecked() {
        return checked;
    }

    public void setChecked(Boolean checked) {
        this.checked = checked;
    }

}
