package sg.edu.smu.livelabs.mobicom.models.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SURVEY_ENTITY".
 */
public class SurveyEntity {

    private Long id;
    private String title;
    private java.util.Date startTime;
    private java.util.Date endTime;
    private String url;
    private String type;
    private String imageUrl;
    private String status;
    private java.util.Date insertTime;
    private java.util.Date lastUpdated;

    public SurveyEntity() {
    }

    public SurveyEntity(Long id) {
        this.id = id;
    }

    public SurveyEntity(Long id, String title, java.util.Date startTime, java.util.Date endTime, String url, String type, String imageUrl, String status, java.util.Date insertTime, java.util.Date lastUpdated) {
        this.id = id;
        this.title = title;
        this.startTime = startTime;
        this.endTime = endTime;
        this.url = url;
        this.type = type;
        this.imageUrl = imageUrl;
        this.status = status;
        this.insertTime = insertTime;
        this.lastUpdated = lastUpdated;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public java.util.Date getStartTime() {
        return startTime;
    }

    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    public java.util.Date getEndTime() {
        return endTime;
    }

    public void setEndTime(java.util.Date endTime) {
        this.endTime = endTime;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public java.util.Date getInsertTime() {
        return insertTime;
    }

    public void setInsertTime(java.util.Date insertTime) {
        this.insertTime = insertTime;
    }

    public java.util.Date getLastUpdated() {
        return lastUpdated;
    }

    public void setLastUpdated(java.util.Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

}
