package sg.edu.smu.livelabs.mobicom.models.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TOPIC_ENTITY".
 */
public class TopicEntity {

    private Long id;
    private String topicHandle;
    private String userHandle;
    private String title;
    private String text;
    private Long totalLikes;
    private Long totalComments;
    private String userFullName;
    private String userPhotoUrl;
    private java.util.Date createdTime;
    private Boolean liked;
    private Integer type;

    public TopicEntity() {
    }

    public TopicEntity(Long id) {
        this.id = id;
    }

    public TopicEntity(Long id, String topicHandle, String userHandle, String title, String text, Long totalLikes, Long totalComments, String userFullName, String userPhotoUrl, java.util.Date createdTime, Boolean liked, Integer type) {
        this.id = id;
        this.topicHandle = topicHandle;
        this.userHandle = userHandle;
        this.title = title;
        this.text = text;
        this.totalLikes = totalLikes;
        this.totalComments = totalComments;
        this.userFullName = userFullName;
        this.userPhotoUrl = userPhotoUrl;
        this.createdTime = createdTime;
        this.liked = liked;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTopicHandle() {
        return topicHandle;
    }

    public void setTopicHandle(String topicHandle) {
        this.topicHandle = topicHandle;
    }

    public String getUserHandle() {
        return userHandle;
    }

    public void setUserHandle(String userHandle) {
        this.userHandle = userHandle;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Long getTotalLikes() {
        return totalLikes;
    }

    public void setTotalLikes(Long totalLikes) {
        this.totalLikes = totalLikes;
    }

    public Long getTotalComments() {
        return totalComments;
    }

    public void setTotalComments(Long totalComments) {
        this.totalComments = totalComments;
    }

    public String getUserFullName() {
        return userFullName;
    }

    public void setUserFullName(String userFullName) {
        this.userFullName = userFullName;
    }

    public String getUserPhotoUrl() {
        return userPhotoUrl;
    }

    public void setUserPhotoUrl(String userPhotoUrl) {
        this.userPhotoUrl = userPhotoUrl;
    }

    public java.util.Date getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(java.util.Date createdTime) {
        this.createdTime = createdTime;
    }

    public Boolean getLiked() {
        return liked;
    }

    public void setLiked(Boolean liked) {
        this.liked = liked;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
