package sg.edu.smu.livelabs.mobicom.models.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_BADGE_ENTITY".
 */
public class UserBadgeEntity {

    private Long id;
    private Long badgeId;
    private Long badgeChildId;
    private Long userId;
    private java.util.Date insertTime;

    public UserBadgeEntity() {
    }

    public UserBadgeEntity(Long id) {
        this.id = id;
    }

    public UserBadgeEntity(Long id, Long badgeId, Long badgeChildId, Long userId, java.util.Date insertTime) {
        this.id = id;
        this.badgeId = badgeId;
        this.badgeChildId = badgeChildId;
        this.userId = userId;
        this.insertTime = insertTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getBadgeId() {
        return badgeId;
    }

    public void setBadgeId(Long badgeId) {
        this.badgeId = badgeId;
    }

    public Long getBadgeChildId() {
        return badgeChildId;
    }

    public void setBadgeChildId(Long badgeChildId) {
        this.badgeChildId = badgeChildId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public java.util.Date getInsertTime() {
        return insertTime;
    }

    public void setInsertTime(java.util.Date insertTime) {
        this.insertTime = insertTime;
    }

}
